module.exports = {
    REQUEST_USER_NAME: 'REQUEST_USER_NAME',
    REQUEST_ENCRYPT_KEY: 'REQUEST_ENCRYPT_KEY',
    REQUEST_PASSWORD: 'REQUEST_PASSWORD',
    REQUEST_UPDATE_LIST: 'REQUEST_UPDATE_LIST',
    REQUEST_GIST_ITEM: 'REQUEST_GIST_ITEM',

    SHOW_PROGRESS: 'SHOW_PROGRESS',
    SHOW_ERROR: 'SHOW_ERROR',
};
